<a href="https://colab.research.google.com/github/LeenNabkie/x-campagnes-de-marketing-ML-classification/blob/main/%C2%AB%E2%80%8930636_A2021_CODE__11312559.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

########################le nom du logiciel utilisé: Google colab################
################# mo nom est Leen Nabkie #################
##########################et mon matricule est 11312559########################

In [1]:
# Import libraries
## Basic libs
import pandas as pd
import numpy as np
import warnings
import io

## Data Visualization
import seaborn as sns
import matplotlib.pyplot as plt

# Configure libraries
warnings.filterwarnings('ignore')
plt.rcParams['figure.figsize'] = (10, 10)
plt.style.use('seaborn')

# Scalling library:
from sklearn.preprocessing import StandardScaler
# Coding library:
from sklearn.preprocessing import OneHotEncoder

#Decision tree model:
from sklearn import tree

#Random Forest Model:
from sklearn.ensemble import RandomForestClassifier

#GradientBoosting Model:
from sklearn.ensemble import GradientBoostingClassifier



In [2]:
## Loading data
from google.colab import files
uploaded = files.upload()

df_banque = pd.read_csv(io.BytesIO(uploaded['30636_A2021_Train_Valid.csv']))
df_banque.columns = df_banque.columns.str.replace(' ', '')

print(df_banque)

Saving 30636_A2021_Train_Valid.csv to 30636_A2021_Train_Valid.csv
          ID  age           job   marital  ... pdays previous  poutcome subscribed
0          1   31    management    single  ...   187        3   success        yes
1          2   75       retired  divorced  ...    93        5     other         no
2          3   43    technician   married  ...    -1        0   unknown         no
3          4   32    management    single  ...    -1        0   unknown         no
4          5   33   blue-collar   married  ...    -1        0   unknown         no
...      ...  ...           ...       ...  ...   ...      ...       ...        ...
27995  27996   35   blue-collar   married  ...    -1        0   unknown         no
27996  27997   69       retired  divorced  ...    92        3   success         no
27997  27998   55       retired   married  ...    -1        0   unknown         no
27998  27999   36  entrepreneur   married  ...    -1        0   unknown         no
27999  28000   45    

In [3]:
# Drop 'duration' column
df_banque = df_banque.drop('duration', axis=1)

#print(df_banque.info())
df_banque.head()

ID  age          job   marital  ... pdays previous  poutcome subscribed
0   1   31   management    single  ...   187        3   success        yes
1   2   75      retired  divorced  ...    93        5     other         no
2   3   43   technician   married  ...    -1        0   unknown         no
3   4   32   management    single  ...    -1        0   unknown         no
4   5   33  blue-collar   married  ...    -1        0   unknown         no

[5 rows x 17 columns]

In [17]:
df_banque['subscribed'].value_counts()

no     24707
yes     3293
Name: subscribed, dtype: int64

In [4]:
# Missing value:
df_banque.isnull().sum()

ID            0
age           0
job           0
marital       0
education     0
default       0
balance       0
housing       0
loan          0
contact       0
day           0
month         0
campaign      0
pdays         0
previous      0
poutcome      0
subscribed    0
dtype: int64

nos données n’ont pas de valeur manquante 

In [5]:
# Scale Numeric Data
# Make a copy of our df_banque
df_scalled = df_banque.copy()

scaler = StandardScaler()
num_cols = ['age', 'balance', 'day', 'campaign', 'pdays', 'previous']
df_scalled[num_cols] = scaler.fit_transform(df_scalled[num_cols])

df_scalled.head()

ID       age          job   marital  ...     pdays  previous  poutcome subscribed
0   1 -0.934548   management    single  ...  1.485363  1.303759   success        yes
1   2  3.204352      retired  divorced  ...  0.538974  2.373934     other         no
2   3  0.194243   technician   married  ... -0.407415 -0.301503   unknown         no
3   4 -0.840482   management    single  ... -0.407415 -0.301503   unknown         no
4   5 -0.746416  blue-collar   married  ... -0.407415 -0.301503   unknown         no

[5 rows x 17 columns]

In [6]:
# Encode our label column (category) by replacing 'yes' and 'no' with 1 and 0 respectively:
encoder = OneHotEncoder(sparse=False)
cat_cols = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']

# Encode Categorical Data
df_encoded = pd.DataFrame(encoder.fit_transform(df_scalled[cat_cols]))
df_encoded.columns = encoder.get_feature_names(cat_cols)

# Replace Categotical Data with Encoded Data
df_scalled = df_scalled.drop(cat_cols ,axis=1)
df = pd.concat([df_encoded, df_scalled], axis=1)
# Encode target value
df['subscribed'] = df['subscribed'].apply(lambda x: 1 if x == 'yes' else 0)

df.head()

job_admin.  job_blue-collar  ...  previous  subscribed
0         0.0              0.0  ...  1.303759           1
1         0.0              0.0  ...  2.373934           0
2         0.0              0.0  ... -0.301503           0
3         0.0              0.0  ... -0.301503           0
4         0.0              1.0  ... -0.301503           0

[5 rows x 52 columns]

# Split Dataset for Training and Testing

In [7]:
# Select Features
feature = df.drop('subscribed', axis=1)

# Select Target
target = df['subscribed']

# Set Training and Testing Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(feature , target, shuffle = True, test_size=0.2, random_state=1)

In [8]:
print('Shape of training feature:', X_train.shape)
print('Shape of testing feature:', X_test.shape)
print('Shape of training label:', y_train.shape)
print('Shape of training label:', y_test.shape)

Shape of training feature: (22400, 51)
Shape of testing feature: (5600, 51)
Shape of training label: (22400,)
Shape of training label: (5600,)


####Building Modeles:

# 1- Decision tree:

In [9]:
dtc = tree.DecisionTreeClassifier(random_state=0)
dtc.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

# 2-Random Forest:

In [10]:
rf = RandomForestClassifier(random_state=0)
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

# 3- GradientBoostingClassifier:

In [11]:
gb_clf = GradientBoostingClassifier(n_estimators=20, learning_rate=1, max_features=2, max_depth=2, random_state=0)
gb_clf.fit(X_train, y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=1, loss='deviance', max_depth=2,
                           max_features=2, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=20,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

#Evaluate the model's performance by using the following metrics:

# Accuracy, Precision, Recall, confussion matrix

In [12]:
def evaluate_model(model, x_test, y_test):
    from sklearn import metrics

    # Predict Test Data 
    y_pred = model.predict(x_test)

    # Calculate accuracy, precision, recall
    acc = metrics.accuracy_score(y_test, y_pred)
    prec = metrics.precision_score(y_test, y_pred)
    rec = metrics.recall_score(y_test, y_pred)

    # Display confussion matrix
    cm = metrics.confusion_matrix(y_test, y_pred)

    return {'acc': acc, 'prec': prec, 'rec': rec, 'cm': cm}

# Evaluate  Decision tree Model:

In [13]:
dtc_eval = evaluate_model(dtc, X_test, y_test)

print('Accuracy of dtc:', dtc_eval['acc'])
print('Precision of dtc:', dtc_eval['prec'])
print('Recall of dtc:', dtc_eval['rec'])
print('Confusion Matrix of dtc:\n', dtc_eval['cm'])

Accuracy of dtc: 0.83125
Precision of dtc: 0.29523809523809524
Recall of dtc: 0.33695652173913043
Confusion Matrix of dtc:
 [[4438  518]
 [ 427  217]]


# Evalute Random Forest Model:

In [14]:
rf_eval = evaluate_model(rf, X_test, y_test)

print('Accuracy of rf:', rf_eval['acc'])
print('Precision of rf:', rf_eval['prec'])
print('Recall of rf:', rf_eval['rec'])
print('Confusion Matrix of rf:\n', rf_eval['cm'])

Accuracy of rf: 0.8973214285714286
Precision of rf: 0.6431535269709544
Recall of rf: 0.2406832298136646
Confusion Matrix of rf:
 [[4870   86]
 [ 489  155]]


# Evaluate GradientBoostingClassifier Model:

In [15]:
gb_clf_eval = evaluate_model(gb_clf, X_test, y_test)

print('Accuracy of gb_clf:', gb_clf_eval['acc'])
print('Precision of gb_clf:', gb_clf_eval['prec'])
print('Recall of gb_clf:', gb_clf_eval['rec'])
print('Confusion Matrix of gb_clf:\n', gb_clf_eval['cm'])

Accuracy of gb_clf: 0.8891071428571429
Precision of gb_clf: 0.5511111111111111
Recall of gb_clf: 0.19254658385093168
Confusion Matrix of gb_clf:
 [[4855  101]
 [ 520  124]]


# Prediction:

In [16]:
df['subscribed_prediction'] = dtc.predict(feature)
df['subscribed_prediction'] = df['subscribed_prediction'].apply(lambda x: 'yes' if x==0 else 'no')

# Save new dataframe into csv file
df.to_csv('subscribed_prediction.csv', index=False)

df.head(10)

job_admin.  job_blue-collar  ...  subscribed  subscribed_prediction
0         0.0              0.0  ...           1                    yes
1         0.0              0.0  ...           0                    yes
2         0.0              0.0  ...           0                    yes
3         0.0              0.0  ...           0                    yes
4         0.0              1.0  ...           0                    yes
5         1.0              0.0  ...           0                    yes
6         0.0              1.0  ...           0                    yes
7         0.0              0.0  ...           0                    yes
8         0.0              0.0  ...           0                    yes
9         0.0              1.0  ...           0                    yes

[10 rows x 53 columns]